// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-pxQRP6HLUnWDRFq2eaF0QsZhcGWwd48',
    appId: '1:570220918797:web:166f40a22a7c3c0fe33d44',
    messagingSenderId: '570220918797',
    projectId: 'chargeledger',
    authDomain: 'chargeledger.firebaseapp.com',
    storageBucket: 'chargeledger.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbxhl5hIVcO3j77SD5MjNyQhXiByFhqWI',
    appId: '1:570220918797:android:d2fa95271c56c43ee33d44',
    messagingSenderId: '570220918797',
    projectId: 'chargeledger',
    storageBucket: 'chargeledger.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDksMQejCgqMtAMkvpMOCk8BNoHXJohV3Q',
    appId: '1:570220918797:ios:6b2c7b37909a784fe33d44',
    messagingSenderId: '570220918797',
    projectId: 'chargeledger',
    storageBucket: 'chargeledger.firebasestorage.app',
    iosBundleId: 'net.chargeledger',
  );
}
